import Foundation

/// Clipboard contents belong to this Mac, never to the snippet library or sync model.
nonisolated struct ClipboardHistoryEntry: Codable, Equatable, Identifiable, Sendable {
    let id: UUID
    let text: String
    var copiedAt: Date

    init(id: UUID = UUID(), text: String, copiedAt: Date = Date()) {
        self.id = id
        self.text = text
        self.copiedAt = copiedAt
    }
}

/// Pure retention and search policy; whitespace and placeholders are always literal.
nonisolated enum ClipboardHistory {
    static let retentionDays = 7
    static let maximumEntries = 1_000
    static let maximumEntryBytes = 256 * 1_024
    static let maximumTotalBytes = 32 * 1_024 * 1_024

    static func accepts(_ text: String) -> Bool {
        !text.isEmpty && text.utf8.count <= maximumEntryBytes
    }

    static func retaining(_ entries: [ClipboardHistoryEntry], now: Date) -> [ClipboardHistoryEntry] {
        let oldest = now.addingTimeInterval(-Double(retentionDays) * 24 * 60 * 60)
        var seen = Set<Data>()
        var seenIDs = Set<UUID>()
        var bytes = 0
        var retained: [ClipboardHistoryEntry] = []
        for var entry in entries.sorted(by: { $0.copiedAt > $1.copiedAt }) {
            guard entry.copiedAt > oldest, accepts(entry.text) else { continue }
            // Moving the system clock backwards must not retain old copies forever.
            if entry.copiedAt > now { entry.copiedAt = now }
            let encoded = Data(entry.text.utf8)
            guard !seen.contains(encoded), !seenIDs.contains(entry.id) else { continue }
            guard retained.count < maximumEntries, bytes + encoded.count <= maximumTotalBytes else { break }
            bytes += encoded.count
            seen.insert(encoded)
            seenIDs.insert(entry.id)
            retained.append(entry)
        }
        return retained
    }

    static func recording(_ text: String, in entries: [ClipboardHistoryEntry], now: Date) -> [ClipboardHistoryEntry] {
        guard accepts(text) else { return retaining(entries, now: now) }
        // Swift String equality equates canonically equivalent Unicode. A clipboard
        // round-trip must preserve the actual copied bytes, including normalization.
        let duplicate = entries.first { $0.text.utf8.elementsEqual(text.utf8) }
        let entry = ClipboardHistoryEntry(id: duplicate?.id ?? UUID(), text: text, copiedAt: now)
        return retaining([entry] + entries.filter { $0.id != entry.id }, now: now)
    }

    static func search(_ query: String, in entries: [ClipboardHistoryEntry]) -> [ClipboardHistoryEntry] {
        let terms = query.split(whereSeparator: \.isWhitespace).map(String.init)
        guard !terms.isEmpty else { return entries }
        return entries.filter { entry in
            terms.allSatisfy { term in
                entry.text.range(of: term, options: [.caseInsensitive, .diacriticInsensitive]) != nil
            }
        }
    }
}

/// Pasteboard flavor filtering is separate from reading text so rejected copies never
/// cross the capture boundary. Markers are a convention, not secret detection.
nonisolated enum ClipboardHistoryCapturePolicy {
    static let internalType = "com.khm.snippets.clipboard-history"
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.SensitiveType",
        "com.apple.is-sensitive",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "public.file-url",
        "NSFilenamesPboardType",
        "com.apple.pasteboard.promised-file-url",
        internalType,
    ]

    static func permits(types: [String], sourceBundleID: String?, excludedBundleIDs: [String]) -> Bool {
        guard Set(types).isDisjoint(with: ignoredTypes) else { return false }
        if let sourceBundleID, excludedBundleIDs.contains(sourceBundleID) { return false }
        return types.contains("public.utf8-plain-text")
    }
}
