//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApprovePairingRequestAlgorithm.
const (
	ApprovePairingRequestAlgorithmSnippetsPairingP256HkdfSha256Aes256gcmV1 ApprovePairingRequestAlgorithm = "snippets-pairing-p256-hkdf-sha256-aes256gcm-v1"
)

// Valid indicates whether the value is a known member of the ApprovePairingRequestAlgorithm enum.
func (e ApprovePairingRequestAlgorithm) Valid() bool {
	switch e {
	case ApprovePairingRequestAlgorithmSnippetsPairingP256HkdfSha256Aes256gcmV1:
		return true
	default:
		return false
	}
}

// Defines values for BatchOutcomeKind.
const (
	BatchOutcomeKindAccepted BatchOutcomeKind = "accepted"
	BatchOutcomeKindConflict BatchOutcomeKind = "conflict"
	BatchOutcomeKindRejected BatchOutcomeKind = "rejected"
)

// Valid indicates whether the value is a known member of the BatchOutcomeKind enum.
func (e BatchOutcomeKind) Valid() bool {
	switch e {
	case BatchOutcomeKindAccepted:
		return true
	case BatchOutcomeKindConflict:
		return true
	case BatchOutcomeKindRejected:
		return true
	default:
		return false
	}
}

// Defines values for ClaimPairingResponseAlgorithm.
const (
	ClaimPairingResponseAlgorithmSnippetsPairingP256HkdfSha256Aes256gcmV1 ClaimPairingResponseAlgorithm = "snippets-pairing-p256-hkdf-sha256-aes256gcm-v1"
)

// Valid indicates whether the value is a known member of the ClaimPairingResponseAlgorithm enum.
func (e ClaimPairingResponseAlgorithm) Valid() bool {
	switch e {
	case ClaimPairingResponseAlgorithmSnippetsPairingP256HkdfSha256Aes256gcmV1:
		return true
	default:
		return false
	}
}

// Defines values for DiscoveryProtocolMajor.
const (
	N2 DiscoveryProtocolMajor = 2
)

// Valid indicates whether the value is a known member of the DiscoveryProtocolMajor enum.
func (e DiscoveryProtocolMajor) Valid() bool {
	switch e {
	case N2:
		return true
	default:
		return false
	}
}

// Defines values for DiscoveryProtocolMinor.
const (
	N0 DiscoveryProtocolMinor = 0
)

// Valid indicates whether the value is a known member of the DiscoveryProtocolMinor enum.
func (e DiscoveryProtocolMinor) Valid() bool {
	switch e {
	case N0:
		return true
	default:
		return false
	}
}

// Defines values for DiscoveryRecordProfile.
const (
	SnippetsWireV1 DiscoveryRecordProfile = "snippets-wire-v1"
)

// Valid indicates whether the value is a known member of the DiscoveryRecordProfile enum.
func (e DiscoveryRecordProfile) Valid() bool {
	switch e {
	case SnippetsWireV1:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAuthenticationRequired   ErrorCode = "authentication_required"
	ErrorCodeConflict                 ErrorCode = "conflict"
	ErrorCodeCursorInvalid            ErrorCode = "cursor_invalid"
	ErrorCodeDatasetReset             ErrorCode = "dataset_reset"
	ErrorCodeDependencyUnavailable    ErrorCode = "dependency_unavailable"
	ErrorCodeForbidden                ErrorCode = "forbidden"
	ErrorCodeIncompatibleVersion      ErrorCode = "incompatible_version"
	ErrorCodeInternalError            ErrorCode = "internal_error"
	ErrorCodeInvalidRequest           ErrorCode = "invalid_request"
	ErrorCodeNotFound                 ErrorCode = "not_found"
	ErrorCodePairingExpired           ErrorCode = "pairing_expired"
	ErrorCodePayloadTooLarge          ErrorCode = "payload_too_large"
	ErrorCodeQuotaExceeded            ErrorCode = "quota_exceeded"
	ErrorCodeRateLimited              ErrorCode = "rate_limited"
	ErrorCodeReauthenticationRequired ErrorCode = "reauthentication_required"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAuthenticationRequired:
		return true
	case ErrorCodeConflict:
		return true
	case ErrorCodeCursorInvalid:
		return true
	case ErrorCodeDatasetReset:
		return true
	case ErrorCodeDependencyUnavailable:
		return true
	case ErrorCodeForbidden:
		return true
	case ErrorCodeIncompatibleVersion:
		return true
	case ErrorCodeInternalError:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodePairingExpired:
		return true
	case ErrorCodePayloadTooLarge:
		return true
	case ErrorCodeQuotaExceeded:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeReauthenticationRequired:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMaxBatchRecords.
const (
	LimitsMaxBatchRecordsN50 LimitsMaxBatchRecords = 50
)

// Valid indicates whether the value is a known member of the LimitsMaxBatchRecords enum.
func (e LimitsMaxBatchRecords) Valid() bool {
	switch e {
	case LimitsMaxBatchRecordsN50:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMaxBlobBytes.
const (
	N900000 LimitsMaxBlobBytes = 900000
)

// Valid indicates whether the value is a known member of the LimitsMaxBlobBytes enum.
func (e LimitsMaxBlobBytes) Valid() bool {
	switch e {
	case N900000:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMaxKeyEnvelopeBytes.
const (
	N4096 LimitsMaxKeyEnvelopeBytes = 4096
)

// Valid indicates whether the value is a known member of the LimitsMaxKeyEnvelopeBytes enum.
func (e LimitsMaxKeyEnvelopeBytes) Valid() bool {
	switch e {
	case N4096:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMaxPageRecords.
const (
	LimitsMaxPageRecordsN50 LimitsMaxPageRecords = 50
)

// Valid indicates whether the value is a known member of the LimitsMaxPageRecords enum.
func (e LimitsMaxPageRecords) Valid() bool {
	switch e {
	case LimitsMaxPageRecordsN50:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMaxPairingSeconds.
const (
	N600 LimitsMaxPairingSeconds = 600
)

// Valid indicates whether the value is a known member of the LimitsMaxPairingSeconds enum.
func (e LimitsMaxPairingSeconds) Valid() bool {
	switch e {
	case N600:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMaxRequestBytes.
const (
	N16777216e07 LimitsMaxRequestBytes = 1.6777216e+07
)

// Valid indicates whether the value is a known member of the LimitsMaxRequestBytes enum.
func (e LimitsMaxRequestBytes) Valid() bool {
	switch e {
	case N16777216e07:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMaxResponseBytes.
const (
	N67108864e07 LimitsMaxResponseBytes = 6.7108864e+07
)

// Valid indicates whether the value is a known member of the LimitsMaxResponseBytes enum.
func (e LimitsMaxResponseBytes) Valid() bool {
	switch e {
	case N67108864e07:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMaxRevisionBytes.
const (
	N256 LimitsMaxRevisionBytes = 256
)

// Valid indicates whether the value is a known member of the LimitsMaxRevisionBytes enum.
func (e LimitsMaxRevisionBytes) Valid() bool {
	switch e {
	case N256:
		return true
	default:
		return false
	}
}

// Defines values for OIDCDiscoveryAuthorizationFlow.
const (
	AuthorizationCodePkce OIDCDiscoveryAuthorizationFlow = "authorization_code_pkce"
)

// Valid indicates whether the value is a known member of the OIDCDiscoveryAuthorizationFlow enum.
func (e OIDCDiscoveryAuthorizationFlow) Valid() bool {
	switch e {
	case AuthorizationCodePkce:
		return true
	default:
		return false
	}
}

// Defines values for PairingState.
const (
	Approved PairingState = "approved"
	Pending  PairingState = "pending"
)

// Valid indicates whether the value is a known member of the PairingState enum.
func (e PairingState) Valid() bool {
	switch e {
	case Approved:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for PutRecoveryEnvelopeRequestAlgorithm.
const (
	PutRecoveryEnvelopeRequestAlgorithmSnippetsRecoveryHkdfSha256Aes256gcmV1 PutRecoveryEnvelopeRequestAlgorithm = "snippets-recovery-hkdf-sha256-aes256gcm-v1"
)

// Valid indicates whether the value is a known member of the PutRecoveryEnvelopeRequestAlgorithm enum.
func (e PutRecoveryEnvelopeRequestAlgorithm) Valid() bool {
	switch e {
	case PutRecoveryEnvelopeRequestAlgorithmSnippetsRecoveryHkdfSha256Aes256gcmV1:
		return true
	default:
		return false
	}
}

// Defines values for RecoveryEnvelopeAlgorithm.
const (
	RecoveryEnvelopeAlgorithmSnippetsRecoveryHkdfSha256Aes256gcmV1 RecoveryEnvelopeAlgorithm = "snippets-recovery-hkdf-sha256-aes256gcm-v1"
)

// Valid indicates whether the value is a known member of the RecoveryEnvelopeAlgorithm enum.
func (e RecoveryEnvelopeAlgorithm) Valid() bool {
	switch e {
	case RecoveryEnvelopeAlgorithmSnippetsRecoveryHkdfSha256Aes256gcmV1:
		return true
	default:
		return false
	}
}

// Defines values for RecoveryEnvelopePurpose.
const (
	Recovery RecoveryEnvelopePurpose = "recovery"
)

// Valid indicates whether the value is a known member of the RecoveryEnvelopePurpose enum.
func (e RecoveryEnvelopePurpose) Valid() bool {
	switch e {
	case Recovery:
		return true
	default:
		return false
	}
}

// Defines values for SpaceRole.
const (
	Owner  SpaceRole = "owner"
	Reader SpaceRole = "reader"
	Writer SpaceRole = "writer"
)

// Valid indicates whether the value is a known member of the SpaceRole enum.
func (e SpaceRole) Valid() bool {
	switch e {
	case Owner:
		return true
	case Reader:
		return true
	case Writer:
		return true
	default:
		return false
	}
}

// ApprovePairingRequest defines model for ApprovePairingRequest.
type ApprovePairingRequest struct {
	Algorithm        ApprovePairingRequestAlgorithm `json:"algorithm"`
	Ciphertext       []byte                         `json:"ciphertext"`
	RecipientKeyHash []byte                         `json:"recipientKeyHash"`
}

// ApprovePairingRequestAlgorithm defines model for ApprovePairingRequest.Algorithm.
type ApprovePairingRequestAlgorithm string

// BatchItem defines model for BatchItem.
type BatchItem struct {
	ExpectedRecordVersion *string    `json:"expectedRecordVersion"`
	Record                WireRecord `json:"record"`
}

// BatchOutcome defines model for BatchOutcome.
type BatchOutcome struct {
	AuthoritativeRecord *ServerRecord    `json:"authoritativeRecord,omitempty"`
	ErrorCode           *ErrorCode       `json:"errorCode,omitempty"`
	Kind                BatchOutcomeKind `json:"kind"`
	RecordVersion       *string          `json:"recordVersion,omitempty"`
	RetryAfterSeconds   *int             `json:"retryAfterSeconds,omitempty"`
	Revision            *string          `json:"revision,omitempty"`
}

// BatchOutcomeKind defines model for BatchOutcome.Kind.
type BatchOutcomeKind string

// BatchRequest defines model for BatchRequest.
type BatchRequest struct {
	Items []BatchItem `json:"items"`
}

// BatchResponse defines model for BatchResponse.
type BatchResponse struct {
	Outcomes []BatchOutcome `json:"outcomes"`
	Partial  bool           `json:"partial"`
	Scope    Scope          `json:"scope"`
}

// ChangesPage defines model for ChangesPage.
type ChangesPage struct {
	Cursor       string         `json:"cursor"`
	FullSnapshot bool           `json:"fullSnapshot"`
	HasMore      bool           `json:"hasMore"`
	Records      []ServerRecord `json:"records"`
	Scope        Scope          `json:"scope"`
}

// ClaimPairingResponse defines model for ClaimPairingResponse.
type ClaimPairingResponse struct {
	Algorithm  ClaimPairingResponseAlgorithm `json:"algorithm"`
	Ciphertext []byte                        `json:"ciphertext"`
	PairingId  openapi_types.UUID            `json:"pairingId"`
	Scope      Scope                         `json:"scope"`
}

// ClaimPairingResponseAlgorithm defines model for ClaimPairingResponse.Algorithm.
type ClaimPairingResponseAlgorithm string

// CreatePairingRequest defines model for CreatePairingRequest.
type CreatePairingRequest struct {
	ExpiresInSeconds   int    `json:"expiresInSeconds"`
	Nonce              []byte `json:"nonce"`
	RecipientPublicKey []byte `json:"recipientPublicKey"`
}

// Discovery defines model for Discovery.
type Discovery struct {
	ApiBase          string                 `json:"apiBase"`
	Capabilities     []string               `json:"capabilities"`
	Limits           Limits                 `json:"limits"`
	Oidc             OIDCDiscovery          `json:"oidc"`
	ProtocolMajor    DiscoveryProtocolMajor `json:"protocolMajor"`
	ProtocolMinor    DiscoveryProtocolMinor `json:"protocolMinor"`
	RecordProfile    DiscoveryRecordProfile `json:"recordProfile"`
	ServerInstanceId openapi_types.UUID     `json:"serverInstanceId"`
	ServerVersion    string                 `json:"serverVersion"`
}

// DiscoveryProtocolMajor defines model for Discovery.ProtocolMajor.
type DiscoveryProtocolMajor int

// DiscoveryProtocolMinor defines model for Discovery.ProtocolMinor.
type DiscoveryProtocolMinor int

// DiscoveryRecordProfile defines model for Discovery.RecordProfile.
type DiscoveryRecordProfile string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Limits defines model for Limits.
type Limits struct {
	MaxBatchRecords     LimitsMaxBatchRecords     `json:"maxBatchRecords"`
	MaxBlobBytes        LimitsMaxBlobBytes        `json:"maxBlobBytes"`
	MaxKeyEnvelopeBytes LimitsMaxKeyEnvelopeBytes `json:"maxKeyEnvelopeBytes"`
	MaxPageRecords      LimitsMaxPageRecords      `json:"maxPageRecords"`
	MaxPairingSeconds   LimitsMaxPairingSeconds   `json:"maxPairingSeconds"`
	MaxRequestBytes     LimitsMaxRequestBytes     `json:"maxRequestBytes"`
	MaxResponseBytes    LimitsMaxResponseBytes    `json:"maxResponseBytes"`
	MaxRevisionBytes    LimitsMaxRevisionBytes    `json:"maxRevisionBytes"`
}

// LimitsMaxBatchRecords defines model for Limits.MaxBatchRecords.
type LimitsMaxBatchRecords int

// LimitsMaxBlobBytes defines model for Limits.MaxBlobBytes.
type LimitsMaxBlobBytes int

// LimitsMaxKeyEnvelopeBytes defines model for Limits.MaxKeyEnvelopeBytes.
type LimitsMaxKeyEnvelopeBytes int

// LimitsMaxPageRecords defines model for Limits.MaxPageRecords.
type LimitsMaxPageRecords int

// LimitsMaxPairingSeconds defines model for Limits.MaxPairingSeconds.
type LimitsMaxPairingSeconds int

// LimitsMaxRequestBytes defines model for Limits.MaxRequestBytes.
type LimitsMaxRequestBytes int

// LimitsMaxResponseBytes defines model for Limits.MaxResponseBytes.
type LimitsMaxResponseBytes int

// LimitsMaxRevisionBytes defines model for Limits.MaxRevisionBytes.
type LimitsMaxRevisionBytes int

// OIDCDiscovery defines model for OIDCDiscovery.
type OIDCDiscovery struct {
	AuthorizationFlow        OIDCDiscoveryAuthorizationFlow `json:"authorizationFlow"`
	ClientId                 string                         `json:"clientId"`
	Issuer                   string                         `json:"issuer"`
	MaxAccessTokenAgeSeconds int                            `json:"maxAccessTokenAgeSeconds"`
	Resource                 string                         `json:"resource"`
	Scopes                   []string                       `json:"scopes"`
	StepUpACRValues          []string                       `json:"stepUpACRValues"`
	StepUpAMRValues          []string                       `json:"stepUpAMRValues"`
	StepUpMaxAgeSeconds      int                            `json:"stepUpMaxAgeSeconds"`
}

// OIDCDiscoveryAuthorizationFlow defines model for OIDCDiscovery.AuthorizationFlow.
type OIDCDiscoveryAuthorizationFlow string

// Pairing defines model for Pairing.
type Pairing struct {
	Algorithm          *string            `json:"algorithm,omitempty"`
	AuthenticationTag  string             `json:"authenticationTag"`
	ExpiresAt          time.Time          `json:"expiresAt"`
	Nonce              []byte             `json:"nonce"`
	PairingId          openapi_types.UUID `json:"pairingId"`
	RecipientPublicKey []byte             `json:"recipientPublicKey"`
	State              PairingState       `json:"state"`
}

// PairingState defines model for Pairing.State.
type PairingState string

// PairingResponse defines model for PairingResponse.
type PairingResponse struct {
	Pairing Pairing `json:"pairing"`
	Scope   Scope   `json:"scope"`
}

// Problem defines model for Problem.
type Problem struct {
	Code              ErrorCode          `json:"code"`
	Limit             *int               `json:"limit,omitempty"`
	RequestId         openapi_types.UUID `json:"requestId"`
	RetryAfterSeconds *int               `json:"retryAfterSeconds,omitempty"`
	Status            int                `json:"status"`
	Type              string             `json:"type"`
}

// PutRecoveryEnvelopeRequest defines model for PutRecoveryEnvelopeRequest.
type PutRecoveryEnvelopeRequest struct {
	Algorithm       PutRecoveryEnvelopeRequestAlgorithm `json:"algorithm"`
	Ciphertext      []byte                              `json:"ciphertext"`
	ExpectedVersion *int                                `json:"expectedVersion"`
	KeyEpoch        int                                 `json:"keyEpoch"`
}

// PutRecoveryEnvelopeRequestAlgorithm defines model for PutRecoveryEnvelopeRequest.Algorithm.
type PutRecoveryEnvelopeRequestAlgorithm string

// RecoveryEnvelope defines model for RecoveryEnvelope.
type RecoveryEnvelope struct {
	Algorithm  RecoveryEnvelopeAlgorithm `json:"algorithm"`
	Ciphertext []byte                    `json:"ciphertext"`
	CreatedAt  time.Time                 `json:"createdAt"`
	KeyEpoch   int                       `json:"keyEpoch"`
	Purpose    RecoveryEnvelopePurpose   `json:"purpose"`
	Version    int                       `json:"version"`
}

// RecoveryEnvelopeAlgorithm defines model for RecoveryEnvelope.Algorithm.
type RecoveryEnvelopeAlgorithm string

// RecoveryEnvelopePurpose defines model for RecoveryEnvelope.Purpose.
type RecoveryEnvelopePurpose string

// RecoveryEnvelopeResponse defines model for RecoveryEnvelopeResponse.
type RecoveryEnvelopeResponse struct {
	KeyEpoch int               `json:"keyEpoch"`
	Recovery *RecoveryEnvelope `json:"recovery"`
	Scope    Scope             `json:"scope"`
}

// Scope defines model for Scope.
type Scope struct {
	DatasetGeneration openapi_types.UUID `json:"datasetGeneration"`
	FeedEpoch         openapi_types.UUID `json:"feedEpoch"`
	ScopeBinding      string             `json:"scopeBinding"`
	SpaceId           openapi_types.UUID `json:"spaceId"`
}

// ServerRecord defines model for ServerRecord.
type ServerRecord struct {
	Blob          []byte             `json:"blob"`
	Deleted       bool               `json:"deleted"`
	Id            openapi_types.UUID `json:"id"`
	RecordVersion string             `json:"recordVersion"`
	Rev           string             `json:"rev"`
}

// Space defines model for Space.
type Space struct {
	KeyEpoch int       `json:"keyEpoch"`
	Role     SpaceRole `json:"role"`
	Scope    Scope     `json:"scope"`
}

// SpaceRole defines model for Space.Role.
type SpaceRole string

// SpacesResponse defines model for SpacesResponse.
type SpacesResponse struct {
	Spaces []Space `json:"spaces"`
}

// WireRecord defines model for WireRecord.
type WireRecord struct {
	Blob    []byte             `json:"blob"`
	Deleted bool               `json:"deleted"`
	Id      openapi_types.UUID `json:"id"`
	Rev     string             `json:"rev"`
}

// PairingID defines model for PairingID.
type PairingID = openapi_types.UUID

// SpaceID defines model for SpaceID.
type SpaceID = openapi_types.UUID

// Error defines model for Error.
type Error = Problem

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Problem

// CreateSpaceParams defines parameters for CreateSpace.
type CreateSpaceParams struct {
	IdempotencyKey *openapi_types.UUID `json:"Idempotency-Key,omitempty"`
}

// GetChangesParams defines parameters for GetChanges.
type GetChangesParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePairingJSONRequestBody defines body for CreatePairing for application/json ContentType.
type CreatePairingJSONRequestBody = CreatePairingRequest

// ApprovePairingJSONRequestBody defines body for ApprovePairing for application/json ContentType.
type ApprovePairingJSONRequestBody = ApprovePairingRequest

// SubmitRecordsJSONRequestBody defines body for SubmitRecords for application/json ContentType.
type SubmitRecordsJSONRequestBody = BatchRequest

// PutRecoveryEnvelopeJSONRequestBody defines body for PutRecoveryEnvelope for application/json ContentType.
type PutRecoveryEnvelopeJSONRequestBody = PutRecoveryEnvelopeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /.well-known/snippets-sync)
	GetDiscovery(w http.ResponseWriter, r *http.Request)

	// (GET /health/live)
	GetLiveness(w http.ResponseWriter, r *http.Request)

	// (GET /health/ready)
	GetReadiness(w http.ResponseWriter, r *http.Request)

	// (DELETE /v2/session)
	RevokeCurrentSession(w http.ResponseWriter, r *http.Request)

	// (GET /v2/spaces)
	ListSpaces(w http.ResponseWriter, r *http.Request)

	// (POST /v2/spaces)
	CreateSpace(w http.ResponseWriter, r *http.Request, params CreateSpaceParams)

	// (GET /v2/spaces/{space})
	GetSpace(w http.ResponseWriter, r *http.Request, space SpaceID)

	// (GET /v2/spaces/{space}/changes)
	GetChanges(w http.ResponseWriter, r *http.Request, space SpaceID, params GetChangesParams)

	// (POST /v2/spaces/{space}/pairings)
	CreatePairing(w http.ResponseWriter, r *http.Request, space SpaceID)

	// (DELETE /v2/spaces/{space}/pairings/{pairing})
	CancelPairing(w http.ResponseWriter, r *http.Request, space SpaceID, pairing PairingID)

	// (GET /v2/spaces/{space}/pairings/{pairing})
	GetPairing(w http.ResponseWriter, r *http.Request, space SpaceID, pairing PairingID)

	// (PUT /v2/spaces/{space}/pairings/{pairing}/approval)
	ApprovePairing(w http.ResponseWriter, r *http.Request, space SpaceID, pairing PairingID)

	// (POST /v2/spaces/{space}/pairings/{pairing}/claim)
	ClaimPairing(w http.ResponseWriter, r *http.Request, space SpaceID, pairing PairingID)

	// (POST /v2/spaces/{space}/records/batch)
	SubmitRecords(w http.ResponseWriter, r *http.Request, space SpaceID)

	// (GET /v2/spaces/{space}/recovery-envelope)
	GetRecoveryEnvelope(w http.ResponseWriter, r *http.Request, space SpaceID)

	// (PUT /v2/spaces/{space}/recovery-envelope)
	PutRecoveryEnvelope(w http.ResponseWriter, r *http.Request, space SpaceID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDiscovery operation middleware
func (siw *ServerInterfaceWrapper) GetDiscovery(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDiscovery(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeCurrentSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeCurrentSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSpaces operation middleware
func (siw *ServerInterfaceWrapper) ListSpaces(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSpaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSpace operation middleware
func (siw *ServerInterfaceWrapper) CreateSpace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSpaceParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSpace(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSpace operation middleware
func (siw *ServerInterfaceWrapper) GetSpace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpace(w, r, space)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChanges operation middleware
func (siw *ServerInterfaceWrapper) GetChanges(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChangesParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChanges(w, r, space, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePairing operation middleware
func (siw *ServerInterfaceWrapper) CreatePairing(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePairing(w, r, space)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelPairing operation middleware
func (siw *ServerInterfaceWrapper) CancelPairing(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	// ------------- Path parameter "pairing" -------------
	var pairing PairingID

	err = runtime.BindStyledParameterWithOptions("simple", "pairing", r.PathValue("pairing"), &pairing, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pairing", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelPairing(w, r, space, pairing)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPairing operation middleware
func (siw *ServerInterfaceWrapper) GetPairing(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	// ------------- Path parameter "pairing" -------------
	var pairing PairingID

	err = runtime.BindStyledParameterWithOptions("simple", "pairing", r.PathValue("pairing"), &pairing, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pairing", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPairing(w, r, space, pairing)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApprovePairing operation middleware
func (siw *ServerInterfaceWrapper) ApprovePairing(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	// ------------- Path parameter "pairing" -------------
	var pairing PairingID

	err = runtime.BindStyledParameterWithOptions("simple", "pairing", r.PathValue("pairing"), &pairing, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pairing", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApprovePairing(w, r, space, pairing)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClaimPairing operation middleware
func (siw *ServerInterfaceWrapper) ClaimPairing(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	// ------------- Path parameter "pairing" -------------
	var pairing PairingID

	err = runtime.BindStyledParameterWithOptions("simple", "pairing", r.PathValue("pairing"), &pairing, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pairing", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClaimPairing(w, r, space, pairing)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitRecords operation middleware
func (siw *ServerInterfaceWrapper) SubmitRecords(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitRecords(w, r, space)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecoveryEnvelope operation middleware
func (siw *ServerInterfaceWrapper) GetRecoveryEnvelope(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecoveryEnvelope(w, r, space)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutRecoveryEnvelope operation middleware
func (siw *ServerInterfaceWrapper) PutRecoveryEnvelope(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space" -------------
	var space SpaceID

	err = runtime.BindStyledParameterWithOptions("simple", "space", r.PathValue("space"), &space, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutRecoveryEnvelope(w, r, space)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/.well-known/snippets-sync", wrapper.GetDiscovery)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/live", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/ready", wrapper.GetReadiness)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v2/session", wrapper.RevokeCurrentSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v2/spaces", wrapper.ListSpaces)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v2/spaces", wrapper.CreateSpace)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v2/spaces/{space}", wrapper.GetSpace)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v2/spaces/{space}/changes", wrapper.GetChanges)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v2/spaces/{space}/records/batch", wrapper.SubmitRecords)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v2/spaces/{space}/recovery-envelope", wrapper.GetRecoveryEnvelope)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v2/spaces/{space}/recovery-envelope", wrapper.PutRecoveryEnvelope)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v2/spaces/{space}/pairings", wrapper.CreatePairing)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v2/spaces/{space}/pairings/{pairing}", wrapper.CancelPairing)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v2/spaces/{space}/pairings/{pairing}", wrapper.GetPairing)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v2/spaces/{space}/pairings/{pairing}/approval", wrapper.ApprovePairing)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v2/spaces/{space}/pairings/{pairing}/claim", wrapper.ClaimPairing)

	return m
}

type ErrorApplicationProblemPlusJSONResponse Problem

type ServiceUnavailableApplicationProblemPlusJSONResponse Problem

type GetDiscoveryRequestObject struct {
}

type GetDiscoveryResponseObject interface {
	VisitGetDiscoveryResponse(w http.ResponseWriter) error
}

type GetDiscovery200JSONResponse Discovery

func (response GetDiscovery200JSONResponse) VisitGetDiscoveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiscoverydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetDiscoverydefaultApplicationProblemPlusJSONResponse) VisitGetDiscoveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse Health

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse Health

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response GetReadiness503ApplicationProblemPlusJSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeCurrentSessionRequestObject struct {
}

type RevokeCurrentSessionResponseObject interface {
	VisitRevokeCurrentSessionResponse(w http.ResponseWriter) error
}

type RevokeCurrentSession204Response struct {
}

func (response RevokeCurrentSession204Response) VisitRevokeCurrentSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeCurrentSessiondefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response RevokeCurrentSessiondefaultApplicationProblemPlusJSONResponse) VisitRevokeCurrentSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListSpacesRequestObject struct {
}

type ListSpacesResponseObject interface {
	VisitListSpacesResponse(w http.ResponseWriter) error
}

type ListSpaces200JSONResponse SpacesResponse

func (response ListSpaces200JSONResponse) VisitListSpacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSpacesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListSpacesdefaultApplicationProblemPlusJSONResponse) VisitListSpacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSpaceRequestObject struct {
	Params CreateSpaceParams
}

type CreateSpaceResponseObject interface {
	VisitCreateSpaceResponse(w http.ResponseWriter) error
}

type CreateSpace201JSONResponse Space

func (response CreateSpace201JSONResponse) VisitCreateSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSpacedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateSpacedefaultApplicationProblemPlusJSONResponse) VisitCreateSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpaceRequestObject struct {
	Space SpaceID `json:"space"`
}

type GetSpaceResponseObject interface {
	VisitGetSpaceResponse(w http.ResponseWriter) error
}

type GetSpace200JSONResponse Space

func (response GetSpace200JSONResponse) VisitGetSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpacedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSpacedefaultApplicationProblemPlusJSONResponse) VisitGetSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetChangesRequestObject struct {
	Space  SpaceID `json:"space"`
	Params GetChangesParams
}

type GetChangesResponseObject interface {
	VisitGetChangesResponse(w http.ResponseWriter) error
}

type GetChanges200JSONResponse ChangesPage

func (response GetChanges200JSONResponse) VisitGetChangesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetChangesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetChangesdefaultApplicationProblemPlusJSONResponse) VisitGetChangesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePairingRequestObject struct {
	Space SpaceID `json:"space"`
	Body  *CreatePairingJSONRequestBody
}

type CreatePairingResponseObject interface {
	VisitCreatePairingResponse(w http.ResponseWriter) error
}

type CreatePairing201JSONResponse PairingResponse

func (response CreatePairing201JSONResponse) VisitCreatePairingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePairingdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreatePairingdefaultApplicationProblemPlusJSONResponse) VisitCreatePairingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CancelPairingRequestObject struct {
	Space   SpaceID   `json:"space"`
	Pairing PairingID `json:"pairing"`
}

type CancelPairingResponseObject interface {
	VisitCancelPairingResponse(w http.ResponseWriter) error
}

type CancelPairing204Response struct {
}

func (response CancelPairing204Response) VisitCancelPairingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelPairingdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CancelPairingdefaultApplicationProblemPlusJSONResponse) VisitCancelPairingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetPairingRequestObject struct {
	Space   SpaceID   `json:"space"`
	Pairing PairingID `json:"pairing"`
}

type GetPairingResponseObject interface {
	VisitGetPairingResponse(w http.ResponseWriter) error
}

type GetPairing200JSONResponse PairingResponse

func (response GetPairing200JSONResponse) VisitGetPairingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPairingdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetPairingdefaultApplicationProblemPlusJSONResponse) VisitGetPairingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ApprovePairingRequestObject struct {
	Space   SpaceID   `json:"space"`
	Pairing PairingID `json:"pairing"`
	Body    *ApprovePairingJSONRequestBody
}

type ApprovePairingResponseObject interface {
	VisitApprovePairingResponse(w http.ResponseWriter) error
}

type ApprovePairing200JSONResponse PairingResponse

func (response ApprovePairing200JSONResponse) VisitApprovePairingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApprovePairingdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ApprovePairingdefaultApplicationProblemPlusJSONResponse) VisitApprovePairingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimPairingRequestObject struct {
	Space   SpaceID   `json:"space"`
	Pairing PairingID `json:"pairing"`
}

type ClaimPairingResponseObject interface {
	VisitClaimPairingResponse(w http.ResponseWriter) error
}

type ClaimPairing200JSONResponse ClaimPairingResponse

func (response ClaimPairing200JSONResponse) VisitClaimPairingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimPairingdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ClaimPairingdefaultApplicationProblemPlusJSONResponse) VisitClaimPairingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitRecordsRequestObject struct {
	Space SpaceID `json:"space"`
	Body  *SubmitRecordsJSONRequestBody
}

type SubmitRecordsResponseObject interface {
	VisitSubmitRecordsResponse(w http.ResponseWriter) error
}

type SubmitRecords200JSONResponse BatchResponse

func (response SubmitRecords200JSONResponse) VisitSubmitRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitRecordsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response SubmitRecordsdefaultApplicationProblemPlusJSONResponse) VisitSubmitRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecoveryEnvelopeRequestObject struct {
	Space SpaceID `json:"space"`
}

type GetRecoveryEnvelopeResponseObject interface {
	VisitGetRecoveryEnvelopeResponse(w http.ResponseWriter) error
}

type GetRecoveryEnvelope200JSONResponse RecoveryEnvelopeResponse

func (response GetRecoveryEnvelope200JSONResponse) VisitGetRecoveryEnvelopeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecoveryEnvelopedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetRecoveryEnvelopedefaultApplicationProblemPlusJSONResponse) VisitGetRecoveryEnvelopeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PutRecoveryEnvelopeRequestObject struct {
	Space SpaceID `json:"space"`
	Body  *PutRecoveryEnvelopeJSONRequestBody
}

type PutRecoveryEnvelopeResponseObject interface {
	VisitPutRecoveryEnvelopeResponse(w http.ResponseWriter) error
}

type PutRecoveryEnvelope200JSONResponse RecoveryEnvelopeResponse

func (response PutRecoveryEnvelope200JSONResponse) VisitPutRecoveryEnvelopeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutRecoveryEnvelopedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PutRecoveryEnvelopedefaultApplicationProblemPlusJSONResponse) VisitPutRecoveryEnvelopeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /.well-known/snippets-sync)
	GetDiscovery(ctx context.Context, request GetDiscoveryRequestObject) (GetDiscoveryResponseObject, error)

	// (GET /health/live)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)

	// (GET /health/ready)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)

	// (DELETE /v2/session)
	RevokeCurrentSession(ctx context.Context, request RevokeCurrentSessionRequestObject) (RevokeCurrentSessionResponseObject, error)

	// (GET /v2/spaces)
	ListSpaces(ctx context.Context, request ListSpacesRequestObject) (ListSpacesResponseObject, error)

	// (POST /v2/spaces)
	CreateSpace(ctx context.Context, request CreateSpaceRequestObject) (CreateSpaceResponseObject, error)

	// (GET /v2/spaces/{space})
	GetSpace(ctx context.Context, request GetSpaceRequestObject) (GetSpaceResponseObject, error)

	// (GET /v2/spaces/{space}/changes)
	GetChanges(ctx context.Context, request GetChangesRequestObject) (GetChangesResponseObject, error)

	// (POST /v2/spaces/{space}/pairings)
	CreatePairing(ctx context.Context, request CreatePairingRequestObject) (CreatePairingResponseObject, error)

	// (DELETE /v2/spaces/{space}/pairings/{pairing})
	CancelPairing(ctx context.Context, request CancelPairingRequestObject) (CancelPairingResponseObject, error)

	// (GET /v2/spaces/{space}/pairings/{pairing})
	GetPairing(ctx context.Context, request GetPairingRequestObject) (GetPairingResponseObject, error)

	// (PUT /v2/spaces/{space}/pairings/{pairing}/approval)
	ApprovePairing(ctx context.Context, request ApprovePairingRequestObject) (ApprovePairingResponseObject, error)

	// (POST /v2/spaces/{space}/pairings/{pairing}/claim)
	ClaimPairing(ctx context.Context, request ClaimPairingRequestObject) (ClaimPairingResponseObject, error)

	// (POST /v2/spaces/{space}/records/batch)
	SubmitRecords(ctx context.Context, request SubmitRecordsRequestObject) (SubmitRecordsResponseObject, error)

	// (GET /v2/spaces/{space}/recovery-envelope)
	GetRecoveryEnvelope(ctx context.Context, request GetRecoveryEnvelopeRequestObject) (GetRecoveryEnvelopeResponseObject, error)

	// (PUT /v2/spaces/{space}/recovery-envelope)
	PutRecoveryEnvelope(ctx context.Context, request PutRecoveryEnvelopeRequestObject) (PutRecoveryEnvelopeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDiscovery operation middleware
func (sh *strictHandler) GetDiscovery(w http.ResponseWriter, r *http.Request) {
	var request GetDiscoveryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDiscovery(ctx, request.(GetDiscoveryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDiscovery")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDiscoveryResponseObject); ok {
		if err := validResponse.VisitGetDiscoveryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeCurrentSession operation middleware
func (sh *strictHandler) RevokeCurrentSession(w http.ResponseWriter, r *http.Request) {
	var request RevokeCurrentSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeCurrentSession(ctx, request.(RevokeCurrentSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeCurrentSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeCurrentSessionResponseObject); ok {
		if err := validResponse.VisitRevokeCurrentSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSpaces operation middleware
func (sh *strictHandler) ListSpaces(w http.ResponseWriter, r *http.Request) {
	var request ListSpacesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSpaces(ctx, request.(ListSpacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSpaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSpacesResponseObject); ok {
		if err := validResponse.VisitListSpacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSpace operation middleware
func (sh *strictHandler) CreateSpace(w http.ResponseWriter, r *http.Request, params CreateSpaceParams) {
	var request CreateSpaceRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSpace(ctx, request.(CreateSpaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSpace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSpaceResponseObject); ok {
		if err := validResponse.VisitCreateSpaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSpace operation middleware
func (sh *strictHandler) GetSpace(w http.ResponseWriter, r *http.Request, space SpaceID) {
	var request GetSpaceRequestObject

	request.Space = space

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSpace(ctx, request.(GetSpaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSpace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSpaceResponseObject); ok {
		if err := validResponse.VisitGetSpaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChanges operation middleware
func (sh *strictHandler) GetChanges(w http.ResponseWriter, r *http.Request, space SpaceID, params GetChangesParams) {
	var request GetChangesRequestObject

	request.Space = space
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetChanges(ctx, request.(GetChangesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChanges")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChangesResponseObject); ok {
		if err := validResponse.VisitGetChangesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePairing operation middleware
func (sh *strictHandler) CreatePairing(w http.ResponseWriter, r *http.Request, space SpaceID) {
	var request CreatePairingRequestObject

	request.Space = space

	var body CreatePairingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePairing(ctx, request.(CreatePairingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePairing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePairingResponseObject); ok {
		if err := validResponse.VisitCreatePairingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelPairing operation middleware
func (sh *strictHandler) CancelPairing(w http.ResponseWriter, r *http.Request, space SpaceID, pairing PairingID) {
	var request CancelPairingRequestObject

	request.Space = space
	request.Pairing = pairing

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelPairing(ctx, request.(CancelPairingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelPairing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelPairingResponseObject); ok {
		if err := validResponse.VisitCancelPairingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPairing operation middleware
func (sh *strictHandler) GetPairing(w http.ResponseWriter, r *http.Request, space SpaceID, pairing PairingID) {
	var request GetPairingRequestObject

	request.Space = space
	request.Pairing = pairing

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPairing(ctx, request.(GetPairingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPairing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPairingResponseObject); ok {
		if err := validResponse.VisitGetPairingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApprovePairing operation middleware
func (sh *strictHandler) ApprovePairing(w http.ResponseWriter, r *http.Request, space SpaceID, pairing PairingID) {
	var request ApprovePairingRequestObject

	request.Space = space
	request.Pairing = pairing

	var body ApprovePairingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApprovePairing(ctx, request.(ApprovePairingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApprovePairing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApprovePairingResponseObject); ok {
		if err := validResponse.VisitApprovePairingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ClaimPairing operation middleware
func (sh *strictHandler) ClaimPairing(w http.ResponseWriter, r *http.Request, space SpaceID, pairing PairingID) {
	var request ClaimPairingRequestObject

	request.Space = space
	request.Pairing = pairing

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimPairing(ctx, request.(ClaimPairingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimPairing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClaimPairingResponseObject); ok {
		if err := validResponse.VisitClaimPairingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitRecords operation middleware
func (sh *strictHandler) SubmitRecords(w http.ResponseWriter, r *http.Request, space SpaceID) {
	var request SubmitRecordsRequestObject

	request.Space = space

	var body SubmitRecordsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitRecords(ctx, request.(SubmitRecordsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitRecords")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitRecordsResponseObject); ok {
		if err := validResponse.VisitSubmitRecordsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecoveryEnvelope operation middleware
func (sh *strictHandler) GetRecoveryEnvelope(w http.ResponseWriter, r *http.Request, space SpaceID) {
	var request GetRecoveryEnvelopeRequestObject

	request.Space = space

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecoveryEnvelope(ctx, request.(GetRecoveryEnvelopeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecoveryEnvelope")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecoveryEnvelopeResponseObject); ok {
		if err := validResponse.VisitGetRecoveryEnvelopeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutRecoveryEnvelope operation middleware
func (sh *strictHandler) PutRecoveryEnvelope(w http.ResponseWriter, r *http.Request, space SpaceID) {
	var request PutRecoveryEnvelopeRequestObject

	request.Space = space

	var body PutRecoveryEnvelopeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutRecoveryEnvelope(ctx, request.(PutRecoveryEnvelopeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutRecoveryEnvelope")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutRecoveryEnvelopeResponseObject); ok {
		if err := validResponse.VisitPutRecoveryEnvelopeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Ftbc9u28v8qGP77VupixVYS/Z8cJ219kkw8cdrOHI+PBiJXEmIQYABQtprRdz+DC+/Q1bKbnrzElAhg",
	"97f3xep7EPEk5QyYksHoe5BigRNQIMzTFSaCsNnlW/1AWDAKUqzmQRgwnIB5Mt8HYSDgW0YExMFIiQzC",
	"QEZzSLBeNuUiwSoYBVlG4iAM1DLVS6UyK1erMLhOcQRrz5D620edsNKLZcqZBMPVOyG40H9EnClgSv+J",
	"05SSCCvCWS8VfEIh+fmr5Ex/V570k4BpMAr+r1eC1rPfyt6VXWXPi0FGgqR6u2AUXFAuIUap4IpHnCLQ",
	"BKB7ouaIcYTFhCiBxRLBQwRmDVLwoLqBxgbEgkTwO8MLTCieUHhOws9RjjqKIQUWA4uWiEiUlfR0jQzd",
	"Zvqs8zQVfAFOdz7DtwykJTWOid4Y0yvBUxCKaHlMMZUQBmnlo+8BpjMuiJonjlu9QSAZSVNQsuPUrpMO",
	"zoad+V087cg51n9jkIOz4SxKOouTtiKEQUTSOQgNbk1vJkulNSzBDx+AzdQ8GJ2dDk896wVEJCXA1HtY",
	"/oblfMsup6dhkBBWfWxrf6nXN+39wwoSNfJvi6345CtESlP3Bqtofqkg2RNseEghUhB/hoiL+A8Qklj9",
	"qbAy6J++qjHzYpBTcJNzEwYsozS4tUBxEW/TvD+JAHuoDwn9cbiGuLXsf8pUxBPYV90yNdcoY0UWOUVb",
	"aNeGCSKnPgyMTV/wGLYtfFe8uAqDO8LMScCyRLONI+0BQDMecTalJFLG9X01GFTYrunkIVKr7aDE8nyq",
	"QFxDxFks3S4k0US9Gp72+2YT+3xS7ECYghkIu8WC+M4/G9aOP9lmAAaPtcI9zJcQBUn9j03iKY1oZWz5",
	"0i46sxC4p5IPLARettiwJ23gw0ajPRnhVrf35CW3iH3YCXUeoAim+gT31YRzCpgFxtnzdKueX5uXmsjY",
	"pWHJS3mUD66LOWYzkFd4ti9YUSakjfJVh9x/vU0hw2CaUXrNcCrnXPn5n2P5kQvwf2ntcXchNR1JXUhN",
	"uRwB+pzAMMeoZKjBvFciFJOkiO0H6fEPGtzdwZfxDjnlUQRRHrhXmL8QgNXj0it4SIkAecl8Dn9Yc/fD",
	"vs/fM84ieHT2U0morrIJJdF7WG7Z9FU9nunHHVOq8oSc/LCNgw/vt0RGfAFiua+ap+QNlnWUMkHq/NgI",
	"3dZlnOIJoaQVwypLvUpceo+TYdt7UJIQtdUjfbBvrcKAkzja9vany7cXJUQrg4Ipcz7ir0WZpTV04FOk",
	"4mXCai/3/VmG9lxXgk9JUQfVncc9EbDGPUjjZy+ZVJhFsKuVm0X+5Gq4NZ2vI9Fktrm7h8SwUCIni0KE",
	"TTAaKuPT43fVDDVPOAlbYErisXB+JDS5MDDlaspxwY8+cf13Uy4mJI6BGetS4ynPWCOLtdFm7E4MwiDG",
	"CktQYwES9AuEafXCikwojBcFKileUo7jseJ8TLGYaWa/ZVzhsa6XIba0YQVjg415dK51bA3cHFbUr+NK",
	"8WpOVSAYpmOTwXtT7N8AUzXf0/ylwiqTVS3ld8E2jXGLfOL7UNjuHkQk+MFlnEVS4qg581qYfp/yyZul",
	"gurLr/v635oF72H5ji2A8hSa62y+5V2lU7o9qHLhrhKv3IrhWrpcaGzSdDJ8+fLl4GS4dpXNaZrLhi9P",
	"+q9eVWy+ucwWQM1lpgJqrmgIvQa6Z7ewJcYWgm2GPcz4peWD16d/dT9/UH39l3Ebv1B+XzWL2pfjiMcw",
	"Tu9MeG6HRaojufXde5WZYUCkzEAcFIwT/HAeRSDlF34H7HwGu5TJwzURTPJMRIclBSZvfEw6sLHikwrS",
	"39Pzi89/YJqtP6aq0LumHW7rj1u2PiChsTt/xA9rpPJiezLbLN2tnlREVVG7QgahR6U3KIqf0DYwbSn4",
	"LNEZ62Oqrm2o1wP9FzyzdwNKh8pgFPzn5rzz70Hn9e33YXgyWP3ks1WXW5/Xq7EYK+goknjN+1hVxX6V",
	"3N41yNmJr4umQ3cttdL5hm2LYtsR9/XvmhljpSTcWLm0BZRTUEV+g/YcWLunpe5tvFNwrx21UPaz424v",
	"9uwO7duoNamlsZzcl6zx7yYE76x5j268lllmse7s9evKqlN/fmQ/qdl0JtgoL6RGJhke3eDOX+Pbn3/a",
	"mreabwtqQotvFQ6v6DKl8xedT+QpyVPcFgl3xrM2k/Jri2rp2BLkTSGRytXJHSzfpTya+5esjVvNAysb",
	"7dVdakrkny+KyPTL4n0C0a4yCIM0EymXtWZEzqRv48UmdVgr2/yQcv0u0q1yvoukD4wIu2NVAKMPYMtP",
	"02B0s9kFt5RxFRYtd2Mwq9vjRJgKmgWVPsyuo/1NwrU5fgUGAisn/a2xYQoQF7ju1o1+Q2zCsbk48l4B",
	"miGLnaJWE0C3sEFC6OG6ypMX2+pFyH4QTyifbHEOJ4N6D6PkPQYKCmL/bQ7ZOYd89CXs4rGXp8RmjYug",
	"5Cm00DQJ9MJv5myezPY5rSXH/J6ZsHcviHLlFo7B3347xp0XpzUzXwuAPNALGjvY49LPgF0vb/v9LbfK",
	"7gwf7ZVJin+c5Tyh3rehMj39KBNELa+1LBwKgAWI88w2ee3TLznl//rzS+AGnAyL5tuSlblSqZ2dImzK",
	"jcOvzVA5m0MDNKGExR2puMAzKKbBusgKDmmKJcIsRnewROBCnkRYAOIp/pZBiGwnogMsEstUQYy0uCTK",
	"JGEzpOaAmjchyBq+Pm1KKHQ13URpWwyu3avoeskidH51WckvRsGg2+/2zR1QCgynJBgFL7on3b4px9Tc",
	"wNbr3gOlnTvG71mvOFkumbk0moHJuLS2mQCgw0vwK6iyidiYyxv0+xuG2/YbaqvcSLXH2mykQSTWFbRa",
	"hqheTaMEFNbxKzTSKMb27NVL12r+FGdUraOiYMsWkTW1C0Y3t/q5Nze3Cj1KFrAJrg9kAQykfEq03AWH",
	"B6orwSOQEhGJsKa0u5EX7cSXm5j5DDgmfx83b/NLIOLsyhBsJHrWf7Fdmp5pTC8ci0FPgsxzAeuU2nh8",
	"hgW/g4tMCGDq2r3fwuW07VK+zLX7AAlMu4BIgFFkTLWUhNk0RlghNTfPto2J7OXiYdpbMFVEOa+APxCp",
	"bBR9SvE24rTPvs0baEEkmVBAihvXWDFyiAvjPxCQMEi59EBghzOu3cxydZr6xk03z22iU8w3X8aQpFwB",
	"i5Yd2+PbfbL5tgXzyXFh9k4z26oScYEEpBQvIUYpCKnzDWQ05BhK1vtu/l9t8iZrYPYdV77Sy8fNPej1",
	"nwE9a+7IZKYmviSQTEDIOUmPiVsvsqNzm/Bz03WHIxg6nf6W2XDuVLqYKyuxag3htVI6/1a271rdqcDH",
	"zDAWTc8tndInFXZ1StEj8l8ySpF0Q3Uo1ckfF4iLGOxgPVXYfHpU8bueuW3ab3BVV8VPOB5jRfbimdvg",
	"fxxMfVNuq3rqr0QGqyd0gc2rEl+omXOhOjozipGDHPHp9DiBtiXM3nf312pTXnGBWQT00YINt75a/jzI",
	"Y16nth1sMiwUcSazRMuMZZS2kkwHXGQIp6Z+4wIVi/OPu3b5gQF7nRf8u4HqP6e+5lCbu8L/R/nNJCr7",
	"xjaJjHGkNOBPqsQ9e7wdM08zj3jqvyV6ThEd36P5fxe1k0t7VhU5z3XCiemplSCimCQbwlRl4Px/wEa9",
	"8/M+KSiekAhTukQCVCaYbQ05RyptRZNLquwHVVtHRxWc+9VAb4KV7ff6pXWdTRKiyrG0HyupqP2K6Jkt",
	"r/7LH4/EPzFAKZeuc4vcL2TQlAsECxBLRFiaKdfQO7pszbUsVC5917dwGndyP2T9tfZyc0NJZpusKEej",
	"sKMQkak2vCmZZeLgoBj6I5xnCOKHM5sNgxrPbET7iPVacV1frZPqoRZU7/fV7w5ubrUIbKfNSi4T1N0R",
	"yFGvJ5cs6sIDTlIK3XwQfnW7+m8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
